import '@/app/globals.css';
import { BodyContainer } from '@/components/navigation/BodyContainer';
import { getAuth } from '@/data-accesses/infra/nextAuth';
import { Flowbite, ThemeModeScript, ThemeProps } from 'flowbite-react';
import type { Metadata } from 'next';
import localFont from 'next/font/local';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

/**
 * flowbiteのtheme設定
 */
const theme = {
  theme: {
    button: {
      color: {
        primary: 'bg-primary hover:bg-primary2 text-white',
        error: 'bg-error hover:bg-error2 text-white',
        warn: 'bg-warn hover:bg-warn2 text-black',
      },
    },
  },
} satisfies ThemeProps;

/**
 * アプリのメタデータ
 */
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

/**
 * 全てのページで読み込まれるレイアウト
 * Server Component
 */
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const auth = await getAuth();

  return (
    <html lang='en' className='h-full'>
      <head>
        <ThemeModeScript />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-full`}
      >
        <Flowbite theme={theme}>
          <BodyContainer auth={auth}>{children}</BodyContainer>
        </Flowbite>
      </body>
    </html>
  );
}
